exam/urls.py
from django.conf.urls import url
from . import views
from .form import LoginForm
from django.contrib.auth import views as auth_views

app_name = 'exam'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<exam_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<exam_id>[0-9]+)/submit/$', views.submit, name='submit'),
    url(r'register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', auth_views.login, {'template_name': 'exam/login.html', 'authentication_form': LoginForm},
        name='login'),
    url(r'^report/$', views.report, name='report'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
]

quiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'^exam/', include('exam.urls'))
]

exam/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Exam(models.Model):
    exam_name = models.CharField(max_length=50)
    duration = models.DurationField()
    date_published = models.DateField('date published')

    def __str__(self):
        return self.exam_name


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    option1 = models.CharField(max_length=100, verbose_name='option1', default='none')
    option2 = models.CharField(max_length=100, verbose_name='option2', default='none')
    option3 = models.CharField(max_length=100, verbose_name='option3', default='none')
    option4 = models.CharField(max_length=100, verbose_name='option4', default='none')
    answer = models.PositiveIntegerField(default=1, validators=[MaxValueValidator(4), MinValueValidator(1)])

    def __str__(self):
        return 'Question:' + self.question_text


class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    marks = models.PositiveIntegerField()

    def __str__(self):
        return ' User :' + self.user.username + 'Exam :' + self.exam.exam_name + 'marks:' + str(self.marks)

exam/views.py
from django.shortcuts import get_object_or_404
from .models import Exam, Report
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from .form import UserForm
from django.shortcuts import render, redirect
from django.contrib.admin.views.decorators import staff_member_required


# Create your views here.
@login_required(login_url='/exam/login/')
def index(request):
    exam_list = Exam.objects.all()
    return render(request, 'exam/index.html', {'exam_list': exam_list})


@login_required(login_url='/exam/login/')
def detail(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    return render(request, 'exam/detail.html', {'exam': exam})


def report(request):
    user = request.user
    if user.is_staff:
        result = Report.objects.all()
    else:
        result = Report.objects.filter(user=user)
    return render(request, 'exam/report.html', {'report': result, 'candidate': user})


""""
class user_login(View):
    form_class = UserLogin
    template_name = 'exam/login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('exam:index')

            return render(request, self.template_name, {'form': form})
"""


@login_required(login_url='/exam/login/')
def submit(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    score = 0
    count = exam.question_set.count()

    for questions in exam.question_set.all():
        if request.POST.get(str(questions.pk)):
            response = request.POST.get(str(questions.pk))
            if str(questions.answer) == str(response):
                score += 1
    Report.objects.create(user=request.user, exam=exam, marks=score)
    return render(request, 'exam/submit.html', {'score': score, 'count': count})


class UserFormView(View):
    form_class = UserForm
    template_name = 'exam/registration.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('exam:index')

            return render(request, self.template_name, {'form': form})

exam/templates/exam/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Exam Portal</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'exam/index.css' %}">
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="nav navbar-inverse">

    <div class="container-fluid">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
             <span class="icon-bar"></span>
            <span class="icon-bar"></span>
             <span class="icon-bar"></span>
        </button>
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'exam:index' %}">Insider</a>
        </div>

        <div class="collapse navbar-collapse" id="topnavbar">

            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'exam:index' %}">
                        <span class="glyphicon glyphicon-pencil" arial-hidden="true"></span>&nbsp;Exams
                    </a>
                </li>
                <li class="">
                    <a href="/admin">
                        <span class="glyphicon glyphicon-wrench" arial-hidden="true"></span>&nbsp;Admin
                    </a>
                </li>

            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="search" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

             <ul class="nav navbar-nav navbar-right ">
                 <li >
                    <a href="{% url 'exam:report' %}">
                        <span class="glyphicon glyphicon-list-alt" arial-hidden="true"></span> Report
                    </a>
                </li>
                <li >
                    <a href="{% url 'exam:login' %}">
                        <span class="glyphicon glyphicon-user" arial-hidden="true"></span> Sign-In
                    </a>
                </li>
                <li >
                    <a href="{% url 'exam:logout' %}">
                        <span class="glyphicon glyphicon-off" arial-hidden="true"></span>&nbsp;Log Out
                    </a>
                </li>
            </ul>
        </div>
    </div>

</nav>
{% block body %}
{% endblock %}

</body>
</html>

exam/templates/exam/detail.html
{% extends 'exam/base.html' %}
{% block body %}
<h1 class="page-header text-center text-primary ">{{ exam.exam_name }}</h1>

<form action="{% url 'exam:submit' exam.id %}" method="post">
    {% csrf_token %}
    {% for questions in exam.question_set.all %}
        <p>{{ forloop.counter }}. {{ questions.question_text }}</p>
        <input type="radio" name="{{ questions.id }}" id="{{ questions.id }}1" value="1" />
        <label for="{{ questions.id }}1">{{ questions.option1 }}</label><br />
        <input type="radio" name="{{ questions.id }}" id="{{ questions.id }}2" value="2" />
        <label for="{{ questions.id }}2">{{ questions.option2 }}</label><br />
        <input type="radio" name="{{ questions.id }}" id="{{ questions.id }}3" value="3" />
        <label for="{{ questions.id }}3">{{ questions.option3 }}</label><br />
        <input type="radio" name="{{ questions.id }}" id="{{ questions.id }}4" value="4" />
        <label for="{{ questions.id }}4">{{ questions.option4 }}</label><br />
        <hr>
    {% endfor %}
    <input type="submit" value="Submit" class="btn btn-danger center-block"/>
</form>
{% endblock %}

exam/templates/exam/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="danger">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

exam/templates/exam/index.html
{% extends 'exam/base.html' %}
{% block body %}
{% if exam_list %}

    {% for exam in exam_list %}
        <div class="view"><a href="{% url 'exam:detail' exam.pk %}" class="link">{{ exam.exam_name }}</a>
            <br>
        Date published:<span class="data">{{ exam.date_published}}</span>&nbsp;
            &nbsp;&nbsp;
        Duration:<span class="data">{{ exam.duration }}</span>
        <button class="btn btn-success submit">Submit</button>
        </div>
        <br>
    {% endfor %}

{% else %}
    <p>No Exam available</p>
{% endif %}
{% endblock %}

exam/templates/exam/login.html
{% extends 'exam/base.html' %}


{% block body %}
    {% if form.errors %}

<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}

<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}

<p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="{% url 'exam:login' %}">
{% csrf_token %}

                        <p class="bs-component">
                            <table>
                                <tr>
                                    <td>{{ form.username.label_tag }}</td>
                                    <td>{{ form.username }}</td>
                                </tr>
                                <tr>
                                    <td>{{ form.password.label_tag }}</td>
                                    <td>{{ form.password }}</td>
                                </tr>
                            </table>
                        </p>
                        <p class="bs-component">
                            <center>
                                <input class="btn btn-success btn-sm" type="submit" value="login" />
                            </center>
                        </p>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}


<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>

{% endblock %}

exam/templates/exam/registration.html
{% extends 'exam/base.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'exam/register.css' %}">
{% endblock %}
{% block body %}
    <div class="form">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'exam/form-template.html' %}
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-success">Submit</button>
    </div>
    </form>
    </div>
{% endblock %}

exam/templates/exam/report.html

{% extends 'exam/base.html' %}
{% block body %}
    <table class="table table-striped">
    <tr>
        {% if candidate.is_staff %}
        <th>User ID</th>
        {% endif %}
    <th>Exam Name</th>
    <th>Marks</th>
    </tr>
  {% for result  in report %}
      <tr>
        {% if candidate.is_staff %}
            <td>{{ result.user }}</td>
        {% endif %}
          <td>{{ result.exam }}</td>
          <td> {{ result.marks }}</td>
      </tr>
  {% endfor %}
    </table>
{% endblock %}

exam/templates/exam/submit.html
{% extends 'exam/base.html' %}
{% load staticfiles %}c
{% block css %}
    <link rel="stylesheet" href="{% static 'exam/submit.css' %}">
{% endblock %}
{% block body %}
<div class="content"><p>
    Your Result is
</p>
<span class="result">{{ score }}/{{ count }}</span>
</div>
{% endblock %}